# Generated by Django 4.2.23 on 2025-08-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_teacher_password_teacher_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='studends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('mark', models.IntegerField(default=0)),
            ],
        ),
    ]
